#===========================================================#
title = "HADDOCK3 Scoring Workflow Setup file"
#===========================================================#
[molecules]
mol1 = 'traj_ensemble.pdb'

[identifier]
run = 1

[execution_parameters]
scheme = 'parallel'
nproc = 24


[stage]

[stage.topology]
recipe='default'

[stage.scoring]
recipe='default'

#===========================================================#