#===========================================================#
title = "HADDOCK3 Setup file"
#===========================================================#
[molecules]
mol1 = '1AY7_r_u.pdb'
mol2 = '1AY7_l_u.pdb'

[restraints]
ambig = 'ambig.tbl'

[identifier]
run = 1

[execution_parameters]
scheme = 'parallel'
nproc = 48

[stage]
[stage.topology]
recipe='default'

[stage.rigid_body]
recipe='rigid-body-minimal.cns'
sampling = 1000
params.auto_his = true

[stage.semi_flexible]
recipe='default'
sampling = 400

[stage.water_refinement]
recipe='default'
sampling = 400
#===========================================================#
